version: 2

sources:
  - name: allproducts
    description: "Product information data transformation in DBT"
    database: dbt_airflow_db
    schema: public 

    tables: 
      - name: jumia_products 
        description: "Raw product from warehouse"

        columns: 
        - name: category
          description: "Product category"
          tests: 
            - not_null 
        
        - name: name
          description: "name of the product"
          tests: 
            - not_null 

        - name: date
          description: "Date of crawling the information"

        - name: currency
          description: "Currency is normally in GHS"
          tests: 
            - not_null
            - accepted_values:
                values: ["GHS"]

        - name: price
          description: "Price of the product"
          tests: 
            - not_null

        - name: percentage
          description: "Percentage of the product"

            
