airflowproj:
  target: dev
  outputs:
    dev:
      database: airflow
      password: airflow
      schema: public
      threads: 5
      type: postgres
      user: airflow
      host: host.docker.internal
      port: 5433
  