airflowproj:
  target: dev
  outputs:
    dev:
      database: airflow
      password: '12345'
      schema: public
      threads: 5
      type: postgres
      user: postgres
      host: host.docker.internal
      port: 5432
  